/**
 * src/storage/types.d.ts
 * TypeScript-style type declarations for cross-dev contracts.
 * Shared across: Dev 2 (storage), Dev 3 (voice), Dev 4 (sync), Dev 5 (UI).
 */

// ── Primitives ───────────────────────────────────────────────────────────────

/** UUIDv4 string generated by crypto.randomUUID() */
type UUID = string;

/** ISO-8601 datetime string */
type ISODate = string;

// ── Ball / Innings types (mirrors app.js runtime objects) ───────────────────

export interface BallChip {
  label:     string;   // e.g. "4", "Wd+0", "W", "NB+1"
  chipClass: string;   // e.g. "ball-four", "ball-wide", "ball-wicket"
}

export interface PlayerState {
  name:        string;
  runs:        number;
  balls:       number;
  fours:       number;
  sixes:       number;
  isOut:       boolean;
  dismissal:   string;
  ballHistory: BallChip[];
}

export interface BowlerState {
  name:            string;
  overs:           number;
  ballsInOver:     number;
  maidens:         number;
  runs:            number;
  wickets:         number;
  runsThisOver:    number;
  overHistory:     Array<{ balls: BallChip[]; runs: number }>;
  currentOverBalls: BallChip[];
}

export interface ExtrasState {
  wides:   number;
  noBalls: number;
  byes:    number;
  legByes: number;
}

export interface InningsState {
  battingTeam:        string;
  bowlingTeam:        string;
  totalRuns:          number;
  totalWickets:       number;
  totalBalls:         number;
  extras:             ExtrasState;
  oversLimit:         number;
  batsmen:            PlayerState[];
  bowlers:            BowlerState[];
  bowlingNames:       string[];
  strikerIndex:       number;
  nonStrikerIndex:    number;
  currentBowlerIndex: number;
  thisOver:           BallChip[];
  lastOver:           BallChip[];
  lastOverRuns:       number;
  history:            InningsSnapshot[];  // undo stack
  isComplete:         boolean;
}

/** Minimal snapshot stored in inn.history for undo */
export interface InningsSnapshot {
  totalRuns:          number;
  totalWickets:       number;
  totalBalls:         number;
  extras:             ExtrasState;
  strikerIndex:       number;
  nonStrikerIndex:    number;
  currentBowlerIndex: number;
  thisOver:           BallChip[];
  lastOver:           BallChip[];
  lastOverRuns:       number;
  batsmen:            PlayerState[];
  bowlers:            BowlerState[];
}

// ── Match ────────────────────────────────────────────────────────────────────

export interface MatchState {
  // Dexie primary key
  id:                  UUID;
  _storageKey?:        string;  // legacy localStorage key for migration compat

  // Team info
  team1:               string;
  team2:               string;
  team1Players:        string[];
  team2Players:        string[];
  oversLimit:          number;
  playersPerTeam:      number;
  battingFirstTeam:    string;
  bowlingFirstTeam:    string;

  // Innings
  innings:             InningsState[];
  currentInnings:      number;  // 0 or 1

  // Server sync fields (nullable until synced)
  tournament_id?:      UUID | null;
  team1_id?:           UUID | null;
  team2_id?:           UUID | null;
  toss_winner_id?:     UUID | null;
  toss_decision?:      'bat' | 'bowl' | null;
  status?:             'setup' | 'in_progress' | 'completed';
  result_text?:        string | null;
  winner_id?:          UUID | null;

  // Per-match event sequence counter (incremented by matchRepo.appendMatchEvent)
  local_seq?:          number;

  // Timestamps
  created_at?:         ISODate;
  updated_at?:         ISODate;
  synced_at?:          ISODate | null;

  // Legacy tournament context
  tournamentName?:     string | null;
  currentFixtureIndex?: number;
}

// ── Tournament ───────────────────────────────────────────────────────────────

export interface TournamentTeam {
  id?:      UUID;
  name:     string;
  players?: TournamentPlayer[];
}

export interface TournamentPlayer {
  id?:         UUID;
  name:        string;
  teamName:    string;
}

export interface Fixture {
  team1:       string;
  team2:       string;
  played:      boolean;
  inProgress?: boolean;
  liveScore?:  string;
  result?:     string;
  winner?:     string | null;
  scoreSummary?: string;
  matchData?:  {
    team1Runs:  number;
    team1Balls: number;
    team2Runs:  number;
    team2Balls: number;
  };
}

export interface TournamentState {
  // Dexie primary key
  id:                UUID;

  // Metadata
  name:              string;
  format:            'league' | 'knockout';
  overs:             number;    // legacy field; maps to overs_per_innings
  playersPerTeam:    number;
  squadSize:         number;

  // Nested entities (denormalized for offline-first simplicity)
  teams:             TournamentTeam[];
  fixtures:          Fixture[];

  // Server sync fields
  owner_id?:         UUID | null;
  overs_per_innings?: number;
  status?:           'setup' | 'active' | 'completed';

  // Timestamps
  created_at?:       ISODate;
  updated_at?:       ISODate;
  synced_at?:        ISODate | null;
}

// ── Ball Event (match_events table) ──────────────────────────────────────────

export interface BallEvent {
  id:              UUID;
  match_id:        UUID;
  innings_number:  0 | 1;
  over_number:     number;
  ball_in_over:    number;
  event_type:      'runs' | 'wide' | 'noball' | 'bye' | 'legbye' | 'wicket' | 'innings_end' | 'match_end';
  runs:            number;
  extra_type:      'wide' | 'noball' | 'bye' | 'legbye' | null;
  extra_runs:      number;
  dismissal_type:  string | null;
  batsman_id:      UUID | null;
  bowler_id:       UUID | null;
  fielder_id:      UUID | null;
  seq:             number;   // per-match monotone; managed by matchRepo
  created_at:      ISODate;
}

// ── Voice Command ─────────────────────────────────────────────────────────────

export interface VoiceCommand {
  action: 'runs' | 'extra' | 'wicket' | 'undo' | 'swap' | 'scorecard' | 'change_bowler' | 'change_striker' | 'change_non_striker';
  runs?:           number;
  type?:           string;  // extra type or wicket dismissal type
  additionalRuns?: number;
}

// ── Scoring Command (engine command pattern) ──────────────────────────────────

export interface ScoringCommand {
  type:    'SCORE_RUNS' | 'PROCESS_EXTRA' | 'HANDLE_WICKET' | 'UNDO_LAST_BALL' | 'SWAP_STRIKE';
  payload: object;
  ts:      number;    // Date.now()
  matchId: UUID;
}

// ── Outbox ────────────────────────────────────────────────────────────────────

export interface OutboxEntry {
  local_id?:       number;   // Dexie auto-increment PK
  entity_type:     'tournament' | 'team' | 'player' | 'match' | 'match_event';
  entity_id:       UUID;
  operation:       'upsert' | 'delete';
  payload:         object;
  seq:             number;   // Date.now() for non-events; per-match seq for match_events
  status:          'pending' | 'in_flight' | 'acked' | 'error';
  created_at:      ISODate;
  last_attempt_at: ISODate | null;
  attempt_count:   number;
}

// ── User ──────────────────────────────────────────────────────────────────────

export interface User {
  id:           UUID;
  email:        string;
  display_name: string | null;
  created_at:   ISODate;
}

// ── Player (server-synced normalized player entity) ───────────────────────────

export interface Player {
  id:            UUID;
  team_id:       UUID;
  tournament_id: UUID;
  name:          string;
  jersey_number: number | null;
  created_at:    ISODate;
  updated_at:    ISODate;
}
